#!/usr/bin/env python3
"""Extract the planning chat export into readable markdown, and verify fidelity.

The export is a single-element JSON list holding one chat. Each assistant answer
lives in `content_list` under `phase == "answer"` -- the sibling `content` field
is empty, which is why a naive read of the file looks like the answers are missing.

Usage:
    python extract.py            # write the markdown files
    python extract.py --check    # verify existing files match the source exactly
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
EXPORT = HERE.parent.parent / "chat-export-1786178220416.json"

# Expected character counts, asserted so a silent truncation cannot pass unnoticed.
EXPECTED_USER = [2019, 1002, 2467, 432]
EXPECTED_ANSWER = [63357, 55327, 11447, 55446]

ANSWER_FILES = [
    ("01_architecture.md", "Answer 1 - Architecture and functional deep dive"),
    ("02_delivery_plan.md", "Answer 2 - Phased delivery, design concepts, workflows"),
    ("03_sa_clarifications.md", "Answer 3 - Revision after the South African clarifications"),
    ("04_solution_and_pricing.md", "Answer 4 - Technical solution document and pricing tiers"),
]

USER_FILE = "00_user_requirements.md"


def normalise(text: str) -> str:
    """Collapse CRLF/CR to LF.

    The export mixes line endings. Writing them through Python's text mode on
    Windows would re-translate them and the --check round-trip would never
    settle, so both extraction and comparison work on LF throughout. This is
    the only alteration made to the source text.
    """
    return text.replace("\r\n", "\n").replace("\r", "\n")


def load() -> tuple[list[str], list[str]]:
    """Return (user messages, assistant answers) in timestamp order."""
    chat = json.loads(EXPORT.read_text(encoding="utf-8"))[0]
    messages = sorted(
        chat["chat"]["history"]["messages"].values(),
        key=lambda m: m.get("timestamp", 0),
    )
    users = [m["content"] for m in messages if m["role"] == "user"]
    answers = [
        block["content"]
        for m in messages
        if m["role"] == "assistant"
        for block in (m.get("content_list") or [])
        if block.get("phase") == "answer"
    ]
    return users, answers


def check_source(users: list[str], answers: list[str]) -> list[str]:
    problems = []
    got_user = [len(u) for u in users]
    got_answer = [len(a) for a in answers]
    if got_user != EXPECTED_USER:
        problems.append(f"user message lengths {got_user} != expected {EXPECTED_USER}")
    if got_answer != EXPECTED_ANSWER:
        problems.append(f"answer lengths {got_answer} != expected {EXPECTED_ANSWER}")
    return problems


def body(text: str) -> str:
    """Strip the generated banner so only the source content is compared."""
    marker = "\n<!-- BEGIN SOURCE -->\n"
    return text.split(marker, 1)[1] if marker in text else text


def render_users(users: list[str]) -> str:
    parts = [
        "# Source: customer requirement messages",
        "",
        "Verbatim, in order. These four messages are the requirement source of truth;",
        "everything the assistant produced is derived from them.",
        "",
        "<!-- BEGIN SOURCE -->",
    ]
    for i, text in enumerate(users, start=1):
        parts += [f"\n## Message {i} ({len(text)} chars)\n", normalise(text).strip(), ""]
    return "\n".join(parts) + "\n"


def render_answer(index: int, title: str, text: str) -> str:
    return (
        f"# Source: {title}\n\n"
        f"Generated by Qwen3.8-Max. {len(text)} characters, reproduced verbatim.\n"
        f"This is a **reference blueprint, not the plan** -- see `../01_PRD.md` section 5\n"
        f"for every place the plan overrides it.\n\n"
        "<!-- BEGIN SOURCE -->\n"
        f"{normalise(text)}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify, do not write")
    args = parser.parse_args()

    if not EXPORT.exists():
        print(f"FAIL: export not found at {EXPORT}", file=sys.stderr)
        return 1

    users, answers = load()
    problems = check_source(users, answers)
    if problems:
        for p in problems:
            print(f"FAIL: {p}", file=sys.stderr)
        return 1

    targets = [(USER_FILE, render_users(users))]
    for i, ((name, title), text) in enumerate(zip(ANSWER_FILES, answers)):
        targets.append((name, render_answer(i, title, text)))

    if args.check:
        for name, expected in targets:
            path = HERE / name
            if not path.exists():
                problems.append(f"{name} missing")
            else:
                # Path.read_text() only accepts newline= on 3.13+, so open explicitly.
                with path.open(encoding="utf-8", newline="\n") as fh:
                    actual = fh.read()
                if body(actual) != body(expected):
                    problems.append(f"{name} differs from the source export")
        if problems:
            for p in problems:
                print(f"FAIL: {p}", file=sys.stderr)
            return 1
        print(f"OK: {len(targets)} extracted files match the source export")
        return 0

    for name, content in targets:
        (HERE / name).write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {name} ({len(content)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
