"""Hide test-suite artifacts (courses and podcast episodes) from the demo tenant.

Years of test runs have left ~1,300 published courses named "Catalogue
Test Course <hex>", "Subscription Test Course <hex>" and similar in the
local dev database. They are assigned to the demo tenant, so
`GET /public/courses` returns them and the catalogue is undemoable.

What this does: removes the `course_tenant_assignments` row that makes
each such course *visible to the demo tenant*. That is the narrowest
possible lever —

  * no course, module or lesson is deleted;
  * no order, payment, invoice, entitlement or enrolment is touched
    (they do not depend on the assignment);
  * it is reversible — re-assigning is one INSERT per course, and the
    same matching rules identify the set again.

A course is considered a test artifact only if its title matches one of
TEST_PATTERNS *and* it has no summary/topic (every real programme is
seeded with both by seed_demo_content.py and migration 0029), so a
genuine course can never be caught by a title coincidence.

Dry run by default — prints what it would do and changes nothing:

    apps/api/.venv/Scripts/python.exe scripts/hide_test_courses.py

Apply it:

    apps/api/.venv/Scripts/python.exe scripts/hide_test_courses.py --apply

Local/dev only; refuses to run against a production environment.
"""

from __future__ import annotations

import asyncio
import sys
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sqlalchemy import delete, func, select, text, update
from sqlalchemy.ext.asyncio import AsyncSession
from src.core.config import get_settings
from src.core.db import get_sessionmaker, init_engine, set_tenant
from src.models.article import Article
from src.models.course import Course, CourseTenantAssignment
from src.models.podcast import PodcastEpisode
from src.models.recommendation import Recommendation

TEST_PATTERNS = [
    "Catalogue Test Course%",
    "Subscription Test Course%",
    "Test Course%",
    "Wizard %",
    "Smoke %",
    "%Test Course %",
]


def _is_artifact(title: str, summary: str | None, topic: str | None) -> bool:
    """Title looks generated AND the course carries none of the editorial
    metadata every real programme has. Both must hold."""
    if summary or topic:
        return False
    lowered = title.lower()
    return "test course" in lowered or lowered.startswith("wizard ") or lowered.startswith("smoke ")


def _is_episode_artifact(title: str) -> bool:
    """Podcast episodes carry no editorial metadata to cross-check, so
    the title alone decides — deliberately narrow, matching only the
    shapes the test suite actually generates."""
    lowered = title.lower()
    return lowered.startswith("test episode") or "smoke test episode" in lowered


def _is_article_artifact(title: str) -> bool:
    """Same shape as `_is_episode_artifact` — `tests/test_articles.py`'s
    `_unique_title()` generates "Test Article <hex>"."""
    return title.lower().startswith("test article")


def _is_recommendation_artifact(title: str) -> bool:
    """Same shape again — `tests/test_recommendations.py`'s
    `_unique_title()` generates "Test Recommendation <hex>"."""
    return title.lower().startswith("test recommendation")


DEMO_TENANT: uuid.UUID  # set in main() from the database


async def _demo_tenant(session: AsyncSession) -> uuid.UUID:
    """Resolved by slug, never hardcoded: the demo tenant's id is
    generated by migration 0002, so it differs between databases and
    changes whenever the volume is recreated."""
    tenant_id = (
        await session.execute(text("SELECT id FROM tenants WHERE slug = 'demo'"))
    ).scalar_one_or_none()
    if tenant_id is None:
        raise SystemExit("no 'demo' tenant — run alembic upgrade head first")
    return uuid.UUID(str(tenant_id))


async def main() -> None:
    apply = "--apply" in sys.argv
    settings = get_settings()
    if settings.environment not in ("local", "development", "dev"):
        raise SystemExit(f"refusing to run in ENVIRONMENT={settings.environment!r}")

    init_engine(settings)
    factory = get_sessionmaker()
    async with factory() as session, session.begin():
        # Resolve before set_tenant: the RLS GUC needs the real id.
        global DEMO_TENANT
        DEMO_TENANT = await _demo_tenant(session)
        demo_tenant = DEMO_TENANT
        await set_tenant(session, demo_tenant)

        total_assigned = (
            await session.execute(
                select(func.count())
                .select_from(CourseTenantAssignment)
                .where(CourseTenantAssignment.tenant_id == DEMO_TENANT)
            )
        ).scalar_one()

        rows = (
            await session.execute(
                select(Course.id, Course.title, Course.summary, Course.topic)
                .join(CourseTenantAssignment, CourseTenantAssignment.course_id == Course.id)
                .where(CourseTenantAssignment.tenant_id == DEMO_TENANT)
            )
        ).all()

        artifacts = [r for r in rows if _is_artifact(r.title, r.summary, r.topic)]
        keep = [r for r in rows if not _is_artifact(r.title, r.summary, r.topic)]

        print(f"assigned to the demo tenant : {total_assigned}")
        print(f"test artifacts to hide      : {len(artifacts)}")
        print(f"courses that stay visible   : {len(keep)}")
        print()
        print("staying visible:")
        for r in sorted(keep, key=lambda r: r.title)[:25]:
            print(f"  - {r.title}")
        if len(keep) > 25:
            print(f"  … and {len(keep) - 25} more")

        # --- Podcast episodes -------------------------------------------
        # Same problem, different table: /public/podcasts lists every
        # published episode, and the test suite has left ~100 named
        # "Test Episode <hex>". Podcasts have no tenant-assignment join,
        # so the narrowest lever here is `state` — unpublishing hides the
        # episode without deleting it, and re-publishing restores it.
        episodes = (
            await session.execute(
                select(PodcastEpisode.id, PodcastEpisode.title).where(
                    PodcastEpisode.tenant_id == DEMO_TENANT,
                    PodcastEpisode.state == "published",
                )
            )
        ).all()
        ep_artifacts = [e for e in episodes if _is_episode_artifact(e.title)]
        ep_keep = [e for e in episodes if not _is_episode_artifact(e.title)]

        print()
        print(f"published episodes          : {len(episodes)}")
        print(f"test episodes to unpublish  : {len(ep_artifacts)}")
        print(f"episodes that stay visible  : {len(ep_keep)}")
        for e in sorted(ep_keep, key=lambda e: e.title)[:10]:
            print(f"  - {e.title}")

        # --- Articles -----------------------------------------------------
        # Same problem again: /public/articles lists every published
        # article, and tests/test_articles.py leaves "Test Article <hex>"
        # rows behind. Same lever as episodes — unpublish via state.
        articles = (
            await session.execute(
                select(Article.id, Article.title).where(
                    Article.tenant_id == DEMO_TENANT,
                    Article.state == "published",
                )
            )
        ).all()
        art_artifacts = [a for a in articles if _is_article_artifact(a.title)]
        art_keep = [a for a in articles if not _is_article_artifact(a.title)]

        print()
        print(f"published articles          : {len(articles)}")
        print(f"test articles to unpublish  : {len(art_artifacts)}")
        print(f"articles that stay visible  : {len(art_keep)}")
        for a in sorted(art_keep, key=lambda a: a.title)[:10]:
            print(f"  - {a.title}")

        # --- Recommendations ------------------------------------------------
        # Same lever again: /public/recommendations lists every published
        # row, and tests/test_recommendations.py leaves "Test
        # Recommendation <hex>" rows behind.
        recommendations = (
            await session.execute(
                select(Recommendation.id, Recommendation.title).where(
                    Recommendation.tenant_id == DEMO_TENANT,
                    Recommendation.state == "published",
                )
            )
        ).all()
        rec_artifacts = [r for r in recommendations if _is_recommendation_artifact(r.title)]
        rec_keep = [r for r in recommendations if not _is_recommendation_artifact(r.title)]

        print()
        print(f"published recommendations   : {len(recommendations)}")
        print(f"test recommendations to hide: {len(rec_artifacts)}")
        print(f"recommendations that stay   : {len(rec_keep)}")
        for r in sorted(rec_keep, key=lambda r: r.title)[:10]:
            print(f"  - {r.title}")

        if not apply:
            print()
            print("DRY RUN — nothing changed. Re-run with --apply to hide them.")
            return

        await session.execute(
            delete(CourseTenantAssignment).where(
                CourseTenantAssignment.tenant_id == DEMO_TENANT,
                CourseTenantAssignment.course_id.in_([r.id for r in artifacts]),
            )
        )
        if ep_artifacts:
            await session.execute(
                update(PodcastEpisode)
                .where(PodcastEpisode.id.in_([e.id for e in ep_artifacts]))
                .values(state="draft")
            )
        if art_artifacts:
            await session.execute(
                update(Article)
                .where(Article.id.in_([a.id for a in art_artifacts]))
                .values(state="draft")
            )
        if rec_artifacts:
            await session.execute(
                update(Recommendation)
                .where(Recommendation.id.in_([r.id for r in rec_artifacts]))
                .values(state="draft")
            )
        print()
        print(f"APPLIED — {len(artifacts)} course assignment(s) removed (courses untouched)")
        print(f"          {len(ep_artifacts)} episode(s) unpublished (episodes untouched)")
        print(f"          {len(art_artifacts)} article(s) unpublished (articles untouched)")
        print(f"          {len(rec_artifacts)} recommendation(s) unpublished (untouched otherwise)")


asyncio.run(main())
