"""Create the demo learner and enrol them in a demo programme.

Everything here is resolved or created at run time — no ids are
hardcoded. The tenant is looked up by slug and the learner by email,
both of which survive a database reset; an earlier version pinned UUIDs
that recreating the Docker volume silently invalidated.

The learner dashboard, the player and the credential panel only have
anything to show once someone is enrolled. Buying a course end to end
(order -> EFT -> proof -> finance approval) is the real path and the
test suite covers it; this script exists so a freshly migrated demo
database has a learner without walking that flow by hand.

It grants a course entitlement and an enrolment directly — the same two
rows `services/orders.py` writes on approval — and nothing else: no
order, payment or invoice is fabricated, so the finance figures in the
analytics dashboard stay honest.

    apps/api/.venv/Scripts/python.exe scripts/seed_demo_enrolment.py [slug]

Idempotent, and local/dev only.
"""

from __future__ import annotations

import asyncio
import sys
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession
from src.core.config import get_settings
from src.core.crypto import CryptoBox
from src.core.db import get_sessionmaker, init_engine, set_tenant
from src.core.ids import uuid7
from src.models.commerce import Entitlement
from src.models.course import Course
from src.models.learning import Enrolment
from src.models.rbac import RoleAssignment
from src.services import identity

DEFAULT_SLUG = "leading-through-ambiguity"

# The demo account. Credentials are deliberately visible: this is a local
# development seed and every caller needs to be able to sign in.
DEMO_EMAIL = "thandi.nkosi@example.com"
DEMO_PASSWORD = "DemoLearner123!"  # noqa: S105 - a local dev seed credential, by design
DEMO_NAME = "Thandi Nkosi"
# super_admin so one login can also demo the admin surfaces (wizard,
# analytics). Narrow this to demo a pure learner.
DEMO_ROLES = ("super_admin",)


async def _tenant_id(session: AsyncSession, slug: str = "demo") -> uuid.UUID:
    """By slug, never hardcoded: tenant ids are generated by migration
    0002 and differ between databases."""
    found = (
        await session.execute(text("SELECT id FROM tenants WHERE slug = :s"), {"s": slug})
    ).scalar_one_or_none()
    if found is None:
        raise SystemExit(f"no {slug!r} tenant — run `alembic upgrade head` first")
    return uuid.UUID(str(found))


async def _learner(session: AsyncSession, crypto: CryptoBox, tenant_id: uuid.UUID) -> uuid.UUID:
    """Found by blind-indexed email, created if absent. Emails are
    encrypted at rest, so the lookup goes through the same blind index
    `services/identity.py` uses rather than a plaintext comparison."""
    blind = crypto.blind_index(DEMO_EMAIL.strip().lower())
    found = (
        await session.execute(
            text("SELECT id FROM users WHERE email_blind_index = :b"), {"b": blind}
        )
    ).scalar_one_or_none()
    if found is not None:
        return uuid.UUID(str(found))

    user = await identity.create_user(
        session,
        crypto,
        tenant_id=tenant_id,
        email=DEMO_EMAIL,
        password=DEMO_PASSWORD,
        full_name=DEMO_NAME,
    )
    await session.flush()
    for role in DEMO_ROLES:
        session.add(RoleAssignment(tenant_id=tenant_id, user_id=user.id, role_code=role))
    await session.flush()
    print(f"created {DEMO_EMAIL} ({DEMO_NAME}) with {', '.join(DEMO_ROLES)}")
    return user.id


async def main() -> None:
    slug = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SLUG
    settings = get_settings()
    if settings.environment not in ("local", "development", "dev"):
        raise SystemExit(f"refusing to run in ENVIRONMENT={settings.environment!r}")

    init_engine(settings)
    crypto = CryptoBox(settings.encryption_key_bytes(), settings.blind_index_key_bytes())
    factory = get_sessionmaker()
    async with factory() as session, session.begin():
        tenant_id = await _tenant_id(session)
        await set_tenant(session, tenant_id)

        user_id = await _learner(session, crypto, tenant_id)

        course = (
            await session.execute(select(Course).where(Course.slug == slug))
        ).scalar_one_or_none()
        if course is None:
            raise SystemExit(f"no course with slug {slug!r} — run seed_demo_content.py first")

        existing = (
            await session.execute(
                select(Enrolment).where(
                    Enrolment.user_id == user_id, Enrolment.course_id == course.id
                )
            )
        ).scalar_one_or_none()
        if existing is not None:
            print(f"already enrolled in {slug} (enrolment {existing.id})")
            print(f"sign in as {DEMO_EMAIL} / {DEMO_PASSWORD}")
            return

        entitlement = Entitlement(
            id=uuid7(),
            tenant_id=tenant_id,
            user_id=user_id,
            kind="course",
            target_id=course.id,
        )
        session.add(entitlement)
        await session.flush()

        enrolment = Enrolment(
            id=uuid7(),
            tenant_id=tenant_id,
            user_id=user_id,
            course_id=course.id,
            entitlement_id=entitlement.id,
        )
        session.add(enrolment)
        await session.flush()
        print(f"enrolled in {slug} — enrolment {enrolment.id}")
        print(f"sign in as {DEMO_EMAIL} / {DEMO_PASSWORD}")


asyncio.run(main())
